### ISSUE TITLE
Labels misaligned on items/browse

### ISSUE THREAD

**Issue by apjmason** [DigitalCarleton/omeka-bootswatch-themes#1]
The column headings on [items/browse](http://omeka-dev.carleton.edu/omeka/items/browse) are misaligned There is no left indent so Title shows up over the image, etc.

![image](https://user-images.githubusercontent.com/10544799/66832101-caae7900-ef1e-11e9-8af5-50de4a334de5.png)

**Comment by zhangshyue** [comment]
It's fixed in commit a74f0f970d42bee88303f0f9887481ca7965c37a
