### ISSUE TITLE
items/tags needs styling

### ISSUE THREAD

**Issue by apjmason** [DigitalCarleton/omeka-bootswatch-themes#2]
There is currently only default styling on [items/tags](http://omeka-dev.carleton.edu/omeka/items/tags) so that its menu looks totally different than the other items/browse options

![image](https://user-images.githubusercontent.com/10544799/66832234-1a8d4000-ef1f-11e9-8500-466f3157c7df.png)

Update menus to match [items/browse](http://omeka-dev.carleton.edu/omeka/items/browse) and add tag cloud styling similar to another theme, e.g. Berlin so that more used tags are bigger

**Comment by zhangshyue** [comment]
I believe this issue is solved in commit 9dfd85e778c4c421eed4b78d9928099dad685453
